# Generated by Django 5.0.1 on 2024-02-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('W', 'Windsor'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington'), ('TO', 'Toronto'), ('CH', 'Chatham')], default='CH', max_length=2),
        ),
        migrations.CreateModel(
            name='OrderVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='carapp.buyer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='carapp.vehicle')),
            ],
        ),
    ]
