# Generated by Django 5.0.1 on 2024-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_buyer_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'cancelled'), (1, 'placed'), (2, 'shipped'), (3, 'delivered')], default=1),
        ),
    ]
