# Generated by Django 5.0.1 on 2024-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_ordervehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('link', models.URLField(max_length=100)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
